import type { Emotion } from './types';

export const EMOTIONS: Emotion[] = [
  // Positive Emotions
  { id: 1, name: '기쁘다', questions: ['최근에 있었던 일 중, 생각하면 나도 모르게 미소 짓게 되는 일이 있나요?', '최근 당신의 하루를 완벽하게 만들어준 작은 순간이 있다면 알려주세요.', '다른 사람을 기쁘게 해주었던 경험이 있다면 공유해주세요.'], emoji: '😄', color: 'bg-green-300', imagePrompt: 'A field of vibrant sunflowers under a clear blue sky, radiating happiness and warmth.' },
  { id: 2, name: '설레다', questions: ['요즘 당신의 마음을 설레게 하는 것은 무엇인가요?', '무언가를 시작하기 전, 가장 설렜던 기억이 있다면 무엇인가요?', '앞으로의 계획 중, 생각만 해도 가슴이 두근거리는 일이 있나요?'], emoji: '💓', color: 'bg-pink-300', imagePrompt: 'A sky full of colorful hot air balloons rising at dawn, with soft, glowing light.' },
  { id: 3, name: '들뜨다', questions: ['마치 소풍가기 전날 밤처럼, 기분 좋게 들떴던 순간을 공유해주세요.', '최근에 무언가에 푹 빠져 시간 가는 줄 몰랐던 경험이 있나요?', '지금 당장 어디론가 떠날 수 있다면, 어디로 가고 싶으신가요?'], emoji: '🥳', color: 'bg-yellow-300', imagePrompt: 'A burst of colorful confetti and streamers against a festive, bokeh-lit background.' },
  { id: 4, name: '편안하다', questions: ['생각만 해도 마음이 편안해지는 나만의 장소나 시간이 있나요?', '당신에게 편안함을 주는 사람이나 물건이 있다면 무엇인가요?', '최근에 가장 편안하고 아늑하다고 느꼈던 순간은 언제인가요?'], emoji: '😌', color: 'bg-sky-200', imagePrompt: 'A cozy, sunlit reading nook with a warm cup of tea, a soft blanket, and a view of a tranquil garden.' },
  { id: 5, name: '뿌듯하다', questions: ['최근 "이건 정말 내가 잘했다!"하고 스스로를 칭찬해준 일이 있나요?', '노력의 결실을 맺어 뿌듯했던 경험이 있다면 이야기해주세요.', '다른 사람에게 도움을 주고 뿌듯함을 느꼈던 순간이 있나요?'], emoji: '😎', color: 'bg-green-300', imagePrompt: 'A majestic mountain peak at sunrise, symbolizing achievement and a sense of accomplishment.' },
  { id: 6, name: '활기차다', questions: ['오늘 아침, "오늘 컨디션 좋은데?"라고 느끼게 한 일이 있었나요?', '당신에게 에너지를 불어넣어 주는 활동이나 음식이 있나요?', '가장 활기찼던 시절의 재미있는 에피소드가 있다면 들려주세요.'], emoji: '🔥', color: 'bg-yellow-300', imagePrompt: 'A splash of bright, dynamic colors, like a vibrant abstract painting full of energy and movement.' },
  { id: 7, name: '만족스럽다', questions: ['소소하지만 확실한 만족감을 느꼈던 최근의 순간은 언제인가요?', '스스로의 선택에 만족했던 경험이 있다면 공유해주세요.', '하루를 마무리하며 "오늘 하루 만족스러웠다"고 느꼈던 적이 있나요?'], emoji: '😊', color: 'bg-green-300', imagePrompt: 'A perfectly ripe, dew-kissed fruit hanging from a branch in a lush, green orchard.' },
  { id: 8, name: '감사하다', questions: ['당연하게 생각했던 것들 중, 새삼 고맙게 느껴졌던 경험이 있나요?', '최근 누군가에게 진심으로 감사한 마음을 표현했던 적이 있나요?', '내 삶에 있어 가장 감사하게 생각하는 세 가지는 무엇인가요?'], emoji: '🙏', color: 'bg-sky-200', imagePrompt: 'Hands gently holding a small, glowing light, surrounded by a soft, warm aura.' },
  { id: 12, name: '기대하다', questions: ['곧 다가올 일 중에, 생각만 해도 기다려지는 일이 있나요?', '어릴 적, 가장 손꼽아 기다렸던 날은 언제였나요?', '누군가와의 만남을 기대하며 준비했던 경험이 있나요?'], emoji: '🤩', color: 'bg-yellow-300', imagePrompt: 'A winding path leading towards a beautiful, glowing sunrise over the horizon.' },
  { id: 27, name: '행복하다', questions: ['"이게 행복이지" 라고 느꼈던, 소박하지만 완벽했던 순간을 공유해주세요.', '당신이 정의하는 \'행복\'이란 무엇인가요?', '최근 다른 사람의 행복한 모습을 보고 덩달아 행복해졌던 경험이 있나요?'], emoji: '😇', color: 'bg-pink-300', imagePrompt: 'A serene meadow filled with blooming wildflowers and dancing butterflies under a gentle sun.' },
  { id: 28, name: '홀가분하다', questions: ['오랫동안 신경 쓰던 일이 끝나고 마음이 홀가분해졌던 경험에 대해 이야기해주세요.', '무거운 짐을 내려놓은 것처럼 후련했던 순간이 있다면 언제인가요?', '정리정돈이나 청소를 통해 마음까지 홀가분해졌던 경험이 있나요?'], emoji: '🕊️', color: 'bg-sky-200', imagePrompt: 'A single white feather floating gently in a soft, pastel-colored sky.' },
  { id: 29, name: '흥분하다', questions: ['생각만해도 당신을 흥분하게 하는 신나는 일이 있나요? 부럽습니다! 함께 나눠주세요.', '좋아하는 가수의 콘서트나 스포츠 경기를 보며 흥분했던 기억이 있나요?', '새로운 도전 앞에서 흥분과 긴장을 동시에 느꼈던 경험이 있나요?'], emoji: '🎢', color: 'bg-yellow-300', imagePrompt: 'A dynamic, abstract scene of a roller coaster track made of light, twisting through a starry night sky.' },
  { id: 30, name: '감동하다', questions: ['최근 영화나 책, 혹은 다른 사람의 이야기에서 마음이 뭉클해졌던 순간이 있다면 알려주세요.', '예상치 못한 선물이나 배려에 감동받았던 경험이 있나요?', '아름다운 풍경을 보고 말문이 막힐 정도로 감동했던 적이 있나요?'], emoji: '🥹', color: 'bg-pink-300', imagePrompt: 'A single, glowing lantern floating up into a beautiful twilight sky filled with stars.' },
  { id: 25, name: '뿌듯하다', questions: ['작은 것이라도 괜찮아요. 최근 무언가를 꾸준히 해서 얻은 성취가 있나요?', '새로운 기술을 배우거나 습관을 만들어 뿌듯했던 경험을 공유해주세요.', '오랫동안 계획했던 일을 마침내 실행에 옮겨 뿌듯했던 적이 있나요?'], emoji: '🏆', color: 'bg-green-300', imagePrompt: 'A beautifully crafted, glowing trophy standing on a pedestal, illuminated by a spotlight.' },
  
  // Neutral Emotions
  { id: 9, name: '차분하다', questions: ['복잡했던 머릿속이 차분하게 정리되었던 순간에 대해 이야기해주세요.', '마음을 차분하게 가라앉히기 위해 즐겨 듣는 음악이나 소리가 있나요?', '화가 나거나 복잡한 상황에서 침착하게 대처했던 경험이 있나요?'], emoji: '🧘', color: 'bg-gray-200', imagePrompt: 'A still, clear lake reflecting a peaceful forest and a calm, blue sky like a mirror.' },
  { id: 10, name: '궁금하다', questions: ['최근에 "이건 왜 이렇지?"하고 궁금증이 생겼던 분야나 주제가 있나요?', '어릴 적, 가장 궁금했지만 아직도 답을 모르는 질문이 있나요?', '누군가의 새로운 소식을 듣고 근황이 궁금해졌던 적이 있나요?'], emoji: '🤔', color: 'bg-gray-200', imagePrompt: 'An antique, ornate keyhole with a mysterious, soft light glowing from within.' },
  { id: 11, name: '심심하다', questions: ['아무것도 안하고 있지만, 동시에 무언가 재미있는 일을 하고 싶을 때 주로 뭘 하세요?', '"심심하다"는 생각이 들 때, 가장 먼저 떠오르는 친구가 있나요?', '학창 시절, 수업이 지루할 때 나만의 상상의 나래를 펼쳤던 경험이 있나요?'], emoji: '😶', color: 'bg-gray-200', imagePrompt: 'A simple, minimalist scene of a single raindrop slowly sliding down a window pane on a gray day.' },
  { id: 23, name: '놀랍다', questions: ['예상치 못한 일로 깜짝 놀랐지만, 결과적으로는 즐거웠던 경험이 있나요?', '누군가의 숨겨진 재능이나 새로운 모습을 보고 놀랐던 적이 있나요?', '최근에 접한 뉴스나 정보 중에 가장 놀라웠던 것은 무엇인가요?'], emoji: '😮', color: 'bg-purple-200', imagePrompt: 'A geode cracked open to reveal a stunning, crystalline interior of shimmering purples and blues.' },
  { id: 24, name: '긴장된다', questions: ['중요한 일을 앞두고 긴장될 때, 어떤 방법으로 마음을 다스리나요?', '살면서 가장 긴장했던 순간은 언제였나요? 지금은 웃으며 말할 수 있나요?', '긴장했지만, 막상 부딪혀보니 별거 아니었던 경험이 있나요?'], emoji: '😰', color: 'bg-purple-200', imagePrompt: 'A tightrope walker\'s view, looking down a thin rope stretching into a misty, uncertain distance.' },
  { id: 26, name: '당황하다', questions: ['갑작스러운 상황에 당황했지만, 나중에 생각하니 웃음이 났던 에피소드가 있나요?', '길을 걷다가 우연히 아는 사람을 만났는데 이름이 기억나지 않아 당황했던 적이 있나요?', '실수해서 당황했지만, 주변 사람들의 도움으로 무사히 넘어갔던 경험이 있나요?'], emoji: '😅', color: 'bg-purple-200', imagePrompt: 'A whimsical scene of tangled, colorful threads, representing a jumbled, flustered feeling.' },

  // Negative Emotions
  { id: 13, name: '우울하다', questions: ['마음이 축 가라앉을 때, 나에게 가장 힘이 되어주는 것은 무엇인가요?', '우울한 기분을 떨쳐내기 위해 먹는 \'소울 푸드\'가 있나요?', '힘들 때 들으면 위로가 되는 나만의 노래가 있다면 알려주세요.'], emoji: '😢', color: 'bg-blue-200', imagePrompt: 'A lone, bare tree in a misty, blue-toned landscape on a rainy day.' },
  { id: 14, name: '지치다', questions: ['몸과 마음의 에너지가 방전되었을 때, 당신은 어떻게 충전하나요?', '아무것도 하고 싶지 않을 만큼 지쳤을 때, 나를 다시 일으켜 세운 것은 무엇이었나요?', '열심히 달린 나를 위해 어떤 휴식을 선물하고 싶으신가요?'], emoji: '🔋', color: 'bg-slate-300', imagePrompt: 'A single, burnt-out candle with a wisp of smoke, on a dark, plain background.' },
  { id: 15, name: '불안하다', questions: ['마음이 불안할 때, 나를 다독여주는 나만의 방법이 있다면 알려주세요.', '결과를 알 수 없어 불안했지만, 결국 좋게 마무리되었던 경험이 있나요?', '불안한 마음을 누군가에게 털어놓고 한결 편안해졌던 경험이 있나요?'], emoji: '😟', color: 'bg-blue-200', imagePrompt: 'A chaotic, abstract pattern of sharp, intersecting lines and shadows, creating a sense of unease.' },
  { id: 16, name: '답답하다', questions: ['꽉 막힌 도로처럼 마음이 답답할 때, 어떻게 그 기분을 해소하시나요?', '내 마음을 아무도 알아주지 않는 것 같아 답답했던 적이 있나요?', '답답한 상황을 해결하기 위해 용기를 냈던 경험이 있다면 들려주세요.'], emoji: '😫', color: 'bg-purple-200', imagePrompt: 'A view from inside a thick, foggy forest, where the path ahead is unclear and obscured.' },
  { id: 17, name: '초조하다', questions: ['무언가를 기다리며 초조했던 경험, 그리고 그 결과는 어땠나요?', '시간에 쫓겨 초조했던 기억이 있다면 이야기해주세요.', '중요한 연락을 기다리며 핸드폰만 바라봤던 적이 있나요?'], emoji: '😥', color: 'bg-blue-200', imagePrompt: 'A clock face with its hands blurred, as if time is moving both too fast and too slow.' },
  { id: 18, name: '피곤하다', questions: ['"아, 정말 피곤하다" 느낄 때, 나에게 주는 작은 보상이 있나요?', '피곤함을 싹 잊게 만들었던 즐거운 경험이 있다면 무엇인가요?', '지금 당장 눕고 싶은 곳은 어디인가요?'], emoji: '😴', color: 'bg-slate-300', imagePrompt: 'A soft, out-of-focus image of a cozy bed with crumpled sheets, in a dimly lit, quiet room.' },
  { id: 19, name: '허전하다', questions: ['마음 한구석이 텅 빈 것처럼 느껴질 때, 그 공간을 무엇으로 채우고 싶나요?', '재미있게 보던 드라마나 책이 끝나고 허전함을 느꼈던 적이 있나요?', '허전한 마음을 달래기 위해 나도 모르게 하는 행동이 있나요?'], emoji: '🌬️', color: 'bg-blue-200', imagePrompt: 'A vast, empty room with a single window showing a gray, overcast sky.' },
  { id: 20, name: '외롭다', questions: ['혼자라고 느껴질 때, 당신에게 힘이 되어주는 사람이나 사물이 있나요?', '왁자지껄한 곳에 있지만 문득 외로움을 느꼈던 경험이 있나요?', '외로움을 긍정적인 에너지로 바꾸어 무언가에 몰두했던 경험이 있나요?'], emoji: '👤', color: 'bg-blue-200', imagePrompt: 'A single, small boat adrift in a vast, calm, and empty ocean under a starry night sky.' },
  { id: 21, name: '속상하다', questions: ['속상했던 마음을 누군가에게 털어놓고 후련해졌던 경험이 있나요?', '어릴 적, 사소한 일로 속상해서 펑펑 울었던 기억이 있나요?', '속상한 일이 있을 때, 기분 전환을 위해 하는 나만의 방법이 있나요?'], emoji: '😞', color: 'bg-purple-200', imagePrompt: 'A beautiful, delicate flower with a single, cracked petal, symbolizing a feeling of being hurt.' },
  { id: 22, name: '짜증나다', questions: ['사소한 일에 짜증이 났을 때, 어떻게 기분을 전환하시나요?', '짜증이 확 났다가도, 금방 웃음이 터졌던 재미있는 경험이 있나요?', '"이럴 땐 정말 짜증나!" 하는 나만의 짜증 유발 포인트가 있나요?'], emoji: '😠', color: 'bg-purple-200', imagePrompt: 'An abstract image of a tangled, thorny vine in sharp, contrasting colors of red and black.' },
];